include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    directives_ordering: false
    always_use_package_imports: false
    prefer_relative_imports: false
    avoid_positional_boolean_parameters: false
    always_put_required_named_parameters_first: false
    sort_constructors_first: false
    sort_pub_dependencies: false
    eol_at_end_of_file: false
