name: imposter
description: "A thrilling local multiplayer social deduction game."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI, Icons, & Design System
  cupertino_icons: ^1.0.9
  flutter_svg: ^2.3.0
  flutter_animate: ^4.5.2
  toastification: ^3.2.0

  # State Management & Service Locator
  get_it: ^9.2.1
  flutter_bloc: ^9.1.1

  # Routing & Deep Linking
  go_router: ^17.2.3

  # Networking & HTTP Clients
  dio: ^5.9.2

  # Localization & Internationalization (i18n / l10n)
  intl: ^0.20.2

  # Audio & Media
  audioplayers: ^6.6.0

  # Native Integration, Launchers, & Splash Screens
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.2

  # Development, Simulation, & Diagnostics
  device_preview: ^1.3.1
  skeletonizer: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Static Code Analysis / Linting Rules
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/data/
    - assets/audio/

  fonts:
    - family: ArefRuqaa
      fonts:
        - asset: assets/font/ArefRuqaa/ArefRuqaa-Regular.ttf
        - asset: assets/font/ArefRuqaa/ArefRuqaa-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_splash_icon.png"
  web:
    generate: true
    image_path: "assets/images/logo_splash_icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo_splash_icon.png"

flutter_native_splash:
  color: "#000000"
  image: "assets/images/logo_splash_icon.png"
  android_12:
    image: "assets/images/logo_splash_icon.png"
    color: "#000000"
  web: true
  fullscreen: false


