// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP6r_GRv_u5qOnd6bNox8a4fS6T_yczHM',
    appId: '1:342928056519:web:33e1021db5c076659edee2',
    messagingSenderId: '342928056519',
    projectId: 'imposter-79f42',
    authDomain: 'imposter-79f42.firebaseapp.com',
    storageBucket: 'imposter-79f42.firebasestorage.app',
    measurementId: 'G-2MQGNLZ7R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHKxmDKN4mdSJP7NeualX4iOqO17Z8Xs0',
    appId: '1:342928056519:android:aec5af6877b107779edee2',
    messagingSenderId: '342928056519',
    projectId: 'imposter-79f42',
    storageBucket: 'imposter-79f42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdAbEkwh0D_u8RepVtuHSsGrU-o9sIbu8',
    appId: '1:342928056519:ios:1409fd3748a6b0b09edee2',
    messagingSenderId: '342928056519',
    projectId: 'imposter-79f42',
    storageBucket: 'imposter-79f42.firebasestorage.app',
    iosBundleId: 'com.korya.imposter',
  );
}
